sudo: required
services:
  - docker

before_install:
  - docker build -t tszala/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tszala/react-test npm test -- --coverage

after_success:
  - docker build -t tszala/multi-client ./client
  - docker build -t tszala/multi-server ./server
  - docker build -t tszala/multi-worker ./worker
  - docker build -t tszala/multi-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker
  - docker push tszala/multi-client
  - docker push tszala/multi-server
  - docker push tszala/multi-worker
  - docker push tszala/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-175138270142"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"  